# Generated by Django 4.2 on 2023-04-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='amenorrhee_induite',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='analogue_lh_rh',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='horm_anastrazole',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='horm_exemestane',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='horm_letrozole',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tamoxifene',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='anorexie_mentale',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='arterite_cellules_geantes',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='autres_connectivites',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='bonne_observance',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='bypass',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='castraction_chirurgiale',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='clairance_inferieure_30',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='comorbites_associees',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='corticotherapie_plus_3',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='corticotherapie_plus_7_5',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diabete_type',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='dose_calcium_journaliere',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='fracture_deux_vertebres',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='fracture_fragilite_femoral',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='fracture_non_severe',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='fracture_severe',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='frax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='frax_cancer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hemochromatose',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hepatopathie_chronique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hormonotherapie_choices',
            field=models.CharField(choices=[('0', 'Décapeptyl'), ('1', 'Fémara'), ('2', 'Tamoxifène')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hypercorticisme',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hyperparathyroide',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hyperthyroide',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hypogonadisme',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='information_complementaires',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='insuffisance_hypophysaire',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='lupus',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='maladie_coeliaque',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='maladie_crohn',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='mastocytose',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='menopause',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='polyarthrite_rheumatoide',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='pseudo_polyarthrite_rhizomélique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='rectocolite_ulcero',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='rhumatisme_psoriasique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='spondylarthrite',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='supplem_calcium',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_injectable',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_oraux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_denosumab',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_osteo',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_raloxifene',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_subs_menopause',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_teriparatide',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='vitamine_d',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_extremite_popup',
            field=models.CharField(default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_femur_popup',
            field=models.CharField(default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_hanche_popup',
            field=models.CharField(default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_rachis_popup',
            field=models.CharField(default='Non', max_length=100),
        ),
    ]
