# Generated by Django 4.2 on 2023-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_diagnosis_amenorrhee_induite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='cancer_sein',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
    ]
