# Generated by Django 4.2 on 2023-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_diagnosis_cancer_sein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='frax_cancer',
            field=models.IntegerField(default=0),
        ),
    ]
