# Generated by Django 4.2 on 2023-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_diagnosis_frax_cancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='dose_calcium_journaliere',
            field=models.IntegerField(null=True),
        ),
    ]
