# Generated by Django 4.2 on 2023-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_diagnosis_dose_calcium_journaliere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='frax_cancer',
            field=models.IntegerField(null=True),
        ),
    ]
