# Generated by Django 4.2 on 2023-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_diagnosis_frax_cancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='apport_calcium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_col_femur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_hache',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_rachis',
            field=models.IntegerField(default=0),
        ),
    ]
