# Generated by Django 4.2 on 2023-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_diagnosis_apport_calcium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='frax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='poids',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_col_femur',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_hache',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_rachis',
            field=models.IntegerField(null=True),
        ),
    ]
