# Generated by Django 4.2 on 2023-04-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_diagnosis_frax_alter_diagnosis_poids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='information_complementaires',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
