# Generated by Django 4.2 on 2023-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_diagnosis_information_complementaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_menopause_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_menopause_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='bonne_observance',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='corticotherapie_plus_3',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='corticotherapie_plus_7_5',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hormonotherapie_choices',
            field=models.CharField(blank=True, choices=[('0', 'Décapeptyl'), ('1', 'Fémara'), ('2', 'Tamoxifène')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='supplem_calcium',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_injectable',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_oraux',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_denosumab',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_osteo',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_raloxifene',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_subs_menopause',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_teriparatide',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='vitamine_d',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_extremite_popup',
            field=models.CharField(blank=True, default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_femur_popup',
            field=models.CharField(blank=True, default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_hanche_popup',
            field=models.CharField(blank=True, default='Non', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_rachis_popup',
            field=models.CharField(blank=True, default='Non', max_length=100),
        ),
    ]
