# Generated by Django 4.2 on 2023-06-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_diagnosis_traitement_menopause_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='bonne_observance_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='bonne_observance_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_injectable_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_injectable_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_oraux_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_oraux_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_denosumab_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_denosumab_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_raloxifene_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_raloxifene_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_teriparatide_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_teriparatide_init_date',
            field=models.DateField(null=True),
        ),
    ]
