# Generated by Django 4.2 on 2023-06-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_diagnosis_bonne_observance_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='bonne_observance_end_date',
            new_name='traitement_bonne_end_date',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='bonne_observance_init_date',
            new_name='traitement_bonne_init_date',
        ),
    ]
