# Generated by Django 4.2 on 2023-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_rename_bonne_observance_end_date_diagnosis_traitement_bonne_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_col_femur',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_hache',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='z_score_rachis',
            field=models.FloatField(null=True),
        ),
    ]
