# Generated by Django 4.2 on 2023-06-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_diagnosis_z_score_col_femur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='traitement_bisphosphonates_injectable_end_date',
            new_name='traitement_acide_zoledronique',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='traitement_bisphosphonates_injectable_init_date',
            new_name='traitement_aledronate',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='traitement_bisphosphonates_injectable',
            new_name='traitement_bisphosphonates',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='traitement_bisphosphonates_oraux_end_date',
            new_name='traitement_risedronate',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_oraux',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='traitement_bisphosphonates_oraux_init_date',
        ),
    ]
