# Generated by Django 4.2 on 2023-06-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_rename_traitement_bisphosphonates_injectable_end_date_diagnosis_traitement_acide_zoledronique_and_mo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='traitement_aledronate',
            new_name='traitement_acide_zoledronique_end_date',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_acide_zoledronique_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_aledronate_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_aledronate_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_risedronate_init_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_acide_zoledronique',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
    ]
