# Generated by Django 4.2 on 2023-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_rename_traitement_aledronate_diagnosis_traitement_acide_zoledronique_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_aledronate',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='traitement_risedronate_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='traitement_risedronate',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
    ]
