# Generated by Django 4.2 on 2023-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_diagnosis_traitement_aledronate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='menopause_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
