# Generated by Django 4.2 on 2023-06-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_diagnosis_menopause_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='pseudo_polyarthrite_rhizomélique',
            new_name='pseudo_polyarthrite_rhizomelique',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hormonotherapie_choices',
            field=models.CharField(blank=True, choices=[('0', 'Décapeptyl'), ('1', 'Fémara'), ('2', 'Tamoxifène')], max_length=100),
        ),
    ]
