# Generated by Django 4.2.3 on 2023-07-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0018_rename_pseudo_polyarthrite_rhizomélique_diagnosis_pseudo_polyarthrite_rhizomelique_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="calcium_intake",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest10_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest10_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest11_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest11_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest12_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest12_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest13_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest13_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest14_baguettes_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest14_biscottes_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest14_ficelles_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest15_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest16_barres_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest16_tablettes_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest17_barres_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest17_tablettes_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest18_litres_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest18_verres_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest19_laquelle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Badoit"),
                    ("1", "Contrex"),
                    ("2", "Evian"),
                    ("3", "Perrier"),
                    ("4", "Vichy"),
                    ("5", "Vittel Grande Source"),
                    ("6", "Hépar"),
                    ("7", "Autre"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest19_litres_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest19_verres_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest1_jour_bols",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest1_jour_tasses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest1_semaine_bols",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest1_semaine_tasses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest20_chaque_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest2_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest3_1000_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest3_100_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest3_500_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest4_grands_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest4_petit_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest5_fromage_fois_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest5_fromage_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest6_fromage_fois_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest6_fromage_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest7_fois_jour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest7_fois_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest7_portions_jour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest7_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest8_semaine",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest9_portions_semaine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petites", "Petites"),
                    ("Moyennes", "Moyennes"),
                    ("Grandes", "Grandes"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="quest9_semaine",
            field=models.IntegerField(default=0),
        ),
    ]
