# Generated by Django 4.2.3 on 2023-07-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0019_diagnosis_calcium_intake_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="apport_calcium",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="calcium_intake",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest10_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest11_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest12_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest13_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest14_baguettes_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest14_biscottes_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest14_ficelles_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest15_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest16_barres_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest16_tablettes_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest17_barres_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest17_tablettes_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest18_litres_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest18_verres_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest19_litres_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest19_verres_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest1_jour_bols",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest1_jour_tasses",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest1_semaine_bols",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest1_semaine_tasses",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest20_chaque_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest2_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest3_1000_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest3_100_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest3_500_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest4_grands_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest4_petit_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest5_fromage_fois_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest6_fromage_fois_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest7_fois_jour",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest7_fois_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest8_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="quest9_semaine",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
