# Generated by Django 4.2.3 on 2023-07-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0022_alter_diagnosis_apport_calcium_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="apport_calcium",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="calcium_intake",
            field=models.IntegerField(null=True),
        ),
    ]
