# Generated by Django 4.2 on 2025-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_alter_diagnosis_apport_calcium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='t_score_col_femur',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='t_score_extremite_distale',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='t_score_hache',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='t_score_rachis',
            field=models.FloatField(null=True),
        ),
    ]
